spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: ravi
    password: ravi
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pallenagaraju70@gmail.com
    password: 9848456707
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true